namespace LexiExtract
{
    public enum Languages
    {
        Arabic,
        Armenian,
        Azerbaijani,
        Bengali,
        Bulgarian,
        Chinese,
        Czech,
        Dutch,
        English,
        Filipino,
        Finnish,
        French,
        Georgian,
        German,
        Greek,
        Hebrew,
        Hindi,
        Indonesian,
        Italian,
        Japanese,
        Kurdish,
        Persian,
        Polish,
        Portuguese,
        Romanian,
        Russian,
        Serbian,
        Spanish,
        Swedish,
        Turkish,
        Ukranian,
        Urdu,
        Vietnamese
    }
}
